# Generated by Django 3.1.5 on 2021-01-14 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(auto_now=True)),
                ('check_in_time', models.DateTimeField(verbose_name='check in time')),
                ('check_out_time', models.DateTimeField(verbose_name='check out time')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ata_timer.employee')),
            ],
        ),
    ]
