# Generated by Django 3.1.5 on 2021-01-15 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ata_timer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='check_in_time',
            field=models.DateTimeField(auto_now=True, verbose_name='check in time'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='check_out_time',
            field=models.DateTimeField(null=True, verbose_name='check out time'),
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_date', models.DateField(verbose_name='Vacation date')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ata_timer.employee')),
            ],
        ),
    ]
