# Generated by Django 3.1.5 on 2021-01-16 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ata_timer', '0006_remove_employee_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ata_timer.team'),
        ),
    ]
