# Generated by Django 3.1.5 on 2021-01-18 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ata_timer', '0008_auto_20210118_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='check_in_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='check in time'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='current_date',
            field=models.DateField(auto_now=True, db_index=True),
        ),
    ]
